FROM ros:foxy
RUN . /opt/ros/$ROS_DISTRO/setup.sh
WORKDIR /microros_ws
RUN git clone -b $ROS_DISTRO https://github.com/micro-ROS/micro_ros_setup.git src/micro_ros_setup
RUN sudo apt update && rosdep update
RUN rosdep install --from-paths src --ignore-src -y
RUN sudo apt-get install python3-pip -y
RUN /bin/bash -c "source /opt/ros/$ROS_DISTRO/setup.bash && colcon build"
